name: Build

on:
  workflow_dispatch:

permissions:
    contents: write

run-name: Build

jobs:
  prepare_release:
    name: Create release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create empty release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v3.0
          token: ${{ secrets.GITHUB_TOKEN }}
          target_commitish: main
          draft: true
    outputs:
      release_id: ${{ steps.release.outputs.id }}

  rootfs:
    runs-on: ubuntu-22.04
    name: Build rootfs 
    strategy:
        matrix:
          flavor:
            #- desktop
            - server
          suite:
            #- oracular
            #- noble
            - jammy
    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && apt-get purge needrestart -y && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gnutls-dev gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs libgnutls28-dev device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper libgnutls30 python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools libelf-dev dwarves

      - name: Build
        shell: bash
        run: sudo ./build.sh --suite=${{ matrix.suite }} --flavor=${{ matrix.flavor }} --rootfs-only

      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
            name: ubuntu-${{ matrix.suite == 'jammy' && '22.04' || matrix.suite == 'noble' && '24.04' || matrix.suite == 'oracular' && '24.10' }}-preinstalled-${{ matrix.flavor }}-arm64-rootfs
            path: ./build/ubuntu-${{ matrix.suite == 'jammy' && '22.04' || matrix.suite == 'noble' && '24.04' || matrix.suite == 'oracular' && '24.10' }}-preinstalled-${{ matrix.flavor }}-arm64.rootfs.tar.xz
            if-no-files-found: error

  kernel:
    runs-on: ubuntu-22.04
    name: Build kernel 
    strategy:
        matrix:
          suite:
            #- oracular
            #- noble
            - jammy
    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && apt-get purge needrestart -y && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gnutls-dev gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs libgnutls28-dev device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper libgnutls30 python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools libelf-dev dwarves

      - name: Build
        shell: bash
        run: sudo ./build.sh --suite=${{ matrix.suite }} --kernel-only

      - name: Upload
        uses: actions/upload-artifact@v4.3.3
        with:
            name: linux-rockchip-${{ matrix.suite == 'jammy' && '5.10' || matrix.suite == 'noble' && '6.1' || matrix.suite == 'oracular' && '6.11' }}
            path: ./build/linux-*.deb
            if-no-files-found: error

  build:
    runs-on: ubuntu-22.04
    needs: [prepare_release, rootfs, kernel]
    name: Build image 

    strategy:
      matrix:
        board:
          - h96max-v56
        flavor:
          - server
        suite:
          #- oracular
          #- noble
          - jammy
        exclude:
          - board: armsom-sige5
            suite: oracular

    steps:
      - name: Get more disk space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout LFS
        shell: bash
        run: git lfs fetch && git lfs checkout

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && apt-get purge needrestart -y && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gnutls-dev gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs libgnutls28-dev device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper libgnutls30 python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev dctrl-tools libelf-dev dwarves

      - name: Checkout rootfs
        uses: actions/download-artifact@v4.1.2
        with:
            name: ubuntu-${{ matrix.suite == 'jammy' && '22.04' || matrix.suite == 'noble' && '24.04' || matrix.suite == 'oracular' && '24.10' }}-preinstalled-${{ matrix.flavor }}-arm64-rootfs
            path: ./build/

      - name: Checkout kernel
        uses: actions/download-artifact@v4.1.2
        with:
            name: linux-rockchip-${{ matrix.suite == 'jammy' && '5.10' || matrix.suite == 'noble' && '6.1' || matrix.suite == 'oracular' && '6.11' }}
            path: ./build/

      - name: Build
        shell: bash
        run: sudo ./build.sh --board=${{ matrix.board }} --suite=${{ matrix.suite }} --flavor=${{ matrix.flavor }}

      - name: Upload
        if: needs.prepare_release.outputs.release_id != '' 
        uses: xresloader/upload-to-github-release@v1
        env:
            GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.prepare_release.outputs.release_id }}
          file: images/ubuntu-*-preinstalled-${{ matrix.flavor }}-arm64-${{ matrix.board }}.*
          draft: true
          overwrite: true

      - name: Clean cache
        shell: bash
        run: sync && sudo rm -rf ./images/ ./build/ && sync
